### ISSUE TITLE
how do I read the value returned by GET command?

### ISSUE THREAD

**Issue by raul-gherman** [roku-on-it/redi-rs#2]
`use std::str::FromStr;

use redi_rs::RedisPool;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut pool: RedisPool = RedisPool::from_str("localhost:6379").unwrap();

    let _ = pool.max_connections(10).establish_pool().await?;

    pool.send_command("SET foo bar").await?;
    
    pool.send_command("GET foo").await?; // how do I get "bar" ?

    Ok(())
}`

**Comment by roku-on-it** [comment]
Hi Raul, there is no such feature since I did not implement it. To be honest, this was a side project I made while I was learning Rust, so this should not be used in production whatsoever. 

To answer your question `send_command` function returns connection. I did not implement any function to read the incoming data but since this function returns the connection that was taken from the pool, you can read from it.

Here is the example code for such functionality: https://github.com/roku-on-it/redi-rs/blob/master/examples/read_from_stream.rs

```rust
 let _ = pool.max_connections(10).establish_pool().await?;

    let redis_connection: Rc<RefCell<RedisConnection>> = pool.send_command("SET foo bar").await?;

    let mut redis_connection_guard = redis_connection.borrow_mut();

    let mut buffer = [0; 1024];

    redis_connection_guard.stream.read(&mut buffer).await?;

    println!("Response: {}", String::from_utf8_lossy(&buffer)); // Response: +OK

    let redis_connection: Rc<RefCell<RedisConnection>> = pool.send_command("PING").await?;

    let mut redis_connection_guard = redis_connection.borrow_mut();

    let mut buffer = [0; 1024];

    redis_connection_guard.stream.read(&mut buffer).await?;

    println!("Response: {}", String::from_utf8_lossy(&buffer)); // Response: +PONG
```

**Comment by raul-gherman** [comment]
got it, thank you
